### ISSUE TITLE
Using the online models with pyttsx3 prints a bunch of logs, how to disable them?

### ISSUE THREAD

**Issue by Meshwa428** [gexgd0419/NaturalVoiceSAPIAdapter#14] opened 2024-08-06 10:42 UTC
So i just installed the online voices, and when i tried to use them with pyttsx3 it printed these logs.

How can i disable these logs

```bash
[2024-08-06 16:07:18] [connect] Successful connection
[2024-08-06 16:07:19] [connect] WebSocket Connection [2620:1ec:c11::237]:443 v-2 "WebSocket++/0.8.2" /consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4 101
[2024-08-06 16:07:19] [frame_header] Dispatching write containing 2 message(s) containing 16 header bytes and 722 payload bytes
[2024-08-06 16:07:19] [frame_header] Header Bytes:
[0] (8) 81 FE 01 80 A8 44 1D 7F
[1] (8) 81 FE 01 52 BF 28 9A F6

[2024-08-06 16:07:19] [frame_payload] Payload Bytes:
[0] (384) [1] ≡iI▬┼!n
╔)mEÜt/Kàt%RÿrINÿ~.HÆu$Q¢t(%ÑN^►╞0x◄▄iI♠╪!'▲╪4q▬╦%i▬╟*2§█+sDê'u▲┌7x
ò1i↓à|►u°%i↨Æ7m→═'uQ╦+s↓┴#►uÑNf]╦+s
═<i]Æ??
╤*i↨═7t
è~f]╔1y▬╟f'♦è)x
╔ |
╔
m
┴+s
è~f]╩+r¶┼%o¶φ*|↔─!y]Æ0o
═h?▌*~
▌%i▬╟*_►▌*y▲┌=X◄╔&q→╠f'↓╔(n→äfn→╞0x◄╦!_►▌*y▲┌=X◄╔&q→╠f'
┌1xSè2t
═)x:╞%‼═ ?E▄6h→äfj►┌ _►▌*y▲┌=X◄╔&q→╠f'
┌1x☻äfr
▄4h
╔0xR┼+s►à)mLè91]─%s↑▌%z→è~f]╔1i►∞!i→╦0t►╞f'↓╔(n→╒9`☻
[1] (338) [1] τ♣╬ƒ╥MΘé▐EΩ╠ì↑¿┬Æ↑ó█Å▲╬╟Å↕⌐┴à↓ú╪î↑»¼▓"┬█φMδâ┌[ε┐█↕°└ë↔«╧ë↓∙╬ì►«┴ì◄√└ç▼∙ù█K∙öÄù█ⁿⁿG⌠é┌Fε█δQΩôàIΩå╙A∙ù╦A⌡ÿÉ[Θ¢╙♥Γ¢╙%Éª▐\≥╠╠[≈Ü▓"ùⁿâ[Ωô▐C║Ç┌ZΘƒ╨Fº╤Ä♠¬╤ƒP≈Ü╤[º╤╫\εåà╡ü╚_┤üî♠⌡ä╪¿╞Å↓╡╟ÅΘÅ╤\≥ô╠AΘ╤ƒP≈Ü╤[á¢╠\εàé≥é╦Xá┘É_φüæ_⌐╪╨Z²┘ì↑¬╟ÉEΘé╦[╜╓╟E÷╠╙I⌠æé ÿÆ}╔╤ü¶∞Ö╓K ╓╤I≈ôé ÿÆ}╔█°]π╕┌]Φù╙ñ┐φù√éƒ\≥ƒ≈Ö╥M⌠éƒ\≥ù≥ôƒC⌠ô╚    ª┘╔G≤ò┌▬ª┘╠X ù╘▬

[2024-08-06 16:07:19] [frame_header] Dispatching write containing 1 message(s) containing 6 header bytes and 2 payload bytes
[2024-08-06 16:07:19] [frame_header] Header Bytes:
[0] (6) 88 82 91 3E 00 37

[2024-08-06 16:07:19] [frame_payload] Payload Bytes:
[0] (2) [8] 92 D6

[2024-08-06 16:07:19] [control] Control frame received with opcode 8
[2024-08-06 16:07:19] [error] handle_read_frame error: asio.system:10054 (An existing connection was forcibly closed by the remote host.)
[2024-08-06 16:07:19] [info] asio async_shutdown error: asio.system:10054 (An existing connection was forcibly closed by the remote host.)
[2024-08-06 16:07:19] [disconnect] Disconnect close local:[1006,An existing connection was forcibly closed by the remote host.] remote:[1000]
[2024-08-06 16:07:34] [connect] Successful connection
[2024-08-06 16:07:35] [connect] WebSocket Connection [2620:1ec:c11::237]:443 v-2 "WebSocket++/0.8.2" /consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4 101
[2024-08-06 16:07:35] [frame_header] Dispatching write containing 2 message(s) containing 16 header bytes and 701 payload bytes
[2024-08-06 16:07:35] [frame_header] Header Bytes: 
[0] (8) 81 FE 01 80 46 FA D1 7D
[1] (8) 81 FE 01 3D D6 17 E4 F2

[2024-08-06 16:07:35] [frame_payload] Payload Bytes:
[0] (384) [1] ▲╫à¶+ƒó   'ùíGt╩πIk╩ΘPv╠àLv└ΓJ|╔ΣSv╠Θ'K≡Æ↕(Ä┤‼2╫à♦6ƒδ∟6è╜¶%¢Ñ¶)ö■↨5ò┐FfÖ╣∟4ë┤     {ÅÑ┬▄w▬¢Ñ§|ëí↑#Ö3ö▓ò┐▄wK3¢Ñ¶)öô↕3ö╡∟4âö‼'ÿ╜↑"╪δó↑j╪ó↑(Ä┤‼%ƒô↕3ö╡∟4âö‼'ÿ╜↑"╪δ    4Å┤Qdî╕#ù┤8(¢│◄#₧≤G2êñ↑j╪ª↕4₧ô↕3ö╡∟4âö‼'ÿ╜↑"╪δ 4Å┤j╪2èñ òú►'Ä≤Gd¢ñ↓/òⁿOræ╣k├τ▬$ôÑ'Ä┤P+ò┐↕kùíNdç²_*¢┐→3¢╢↑d└¬_'ÅÑ↕☻ƒÑ↑%Ä╕↕(╪δó↑;ç¼
[1] (317) [1] Ä:░¢╗rùå╖zö╚Σ'╓╞√'▄▀µ!░├µ-╫┼∞$╤▄µ!▄¿█↔╝▀äròç│dÉ╗▓-╘ùαuåæ▓%Ç╩∩s╨ö░våô▓!╨├Σ/Ç├│'üù╡&Θ°òxèå│yÉ▀énöù∞vöé║~çôó~ï£∙dùƒ║<£ƒ║→εó╖cî╚Ñdë₧█↔Θ°Ωdöù╖|─ä│eù¢╣y┘╒τ9╘╒÷oë₧╕d┘╒╛cÉé∞8╦àí`╩àσ9ïÇ▒8╓┬µ&╦├µ8ùï╕cîùÑ~ù╒÷oë₧╕d▐ƒÑcÉüδ0îåóg▐▌∙`ôà°`╫▄╣eâ▌Σ'╘├∙zùåód├╥«zê╚║vèòδ0ü£√B╖╒Φ+Æ¥┐tü╥╕vëùδ0ü£√B╖▀æb¥╝│bûô║0┌▐÷ü╥░bçÖ│s─çª+╦ä╣~çùΦ+╦üªràÖΦ      

[2024-08-06 16:07:35] [frame_header] Dispatching write containing 1 message(s) containing 6 header bytes and 2 payload bytes
[2024-08-06 16:07:35] [frame_header] Header Bytes:
[0] (6) 88 82 78 59 43 06

[2024-08-06 16:07:35] [frame_payload] Payload Bytes:
[0] (2) [8] 7B B1

[2024-08-06 16:07:35] [control] Control frame received with opcode 8
[2024-08-06 16:07:35] [error] handle_read_frame error: asio.system:10054 (An existing connection was forcibly closed by the remote host.)
[2024-08-06 16:07:35] [info] asio async_shutdown error: asio.system:10054 (An existing connection was forcibly closed by the remote host.)
[2024-08-06 16:07:35] [disconnect] Disconnect close local:[1006,An existing connection was forcibly closed by the remote host.] remote:[1000]
```

**Comment by gexgd0419** [comment] 2024-08-06 11:17
Confirmed. This is caused by the [websocketpp](https://github.com/zaphoyd/websocketpp) library I'm using. By default, it will output logs to stdout.

Since the application used for testing is a GUI app and has no console, I didn't notice the problem until now. Thanks for your report. This will be fixed in the next release.

**Comment by gexgd0419** [comment] 2024-08-16 08:24
A new version [v0.2](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2) has been released! This version should fix the issue.

**Closed** 2024-08-17 03:12 UTC
