### ISSUE TITLE
v0.2.3 not installing

### ISSUE THREAD

**Issue by Darkcyde13** [gexgd0419/NaturalVoiceSAPIAdapter#34] opened 2024-12-07 02:15 UTC
v0.2.3 will l not install.  Instead it says Admin privileges are required when I click the 'Install 32bit' or 'Install 64bit', even though I've run it as an Administrator.

Going back to v0.2.0.0 and it all works as expected.

**Comment by gexgd0419** [comment] 2024-12-07 11:43
I'm not able to reproduce the issue on my system, so I need some further information.

- What's the Windows version you are using?
- Does [v0.2.1](https://github.com/gexgd0419/NaturalVoiceSAPIAdapter/releases/tag/v0.2.1) work on your system?
- If you use `regsvr32` to manually register the `NaturalVoiceSAPIAdapter.dll` file, will it succeed?

**Comment by Darkcyde13** [comment] 2024-12-07 14:58
I figured that you probably hadn't seen any problems, as it's been a few weeks since release of v0.2.3.  

- Windows 11 Pro 23H2 build 22631.4541
- v0.2.1 does not work, it has the same problem.
- Using `regsvr32` (64bit version) comes up with an error:
![image](https://github.com/user-attachments/assets/5aaecc09-336a-4624-87af-b188741cbe04)
Looking up this error, it appears to be because it needs to be done in Admin mode, which it was (CMD was run as Administrator).

This is the error I get when using the installer running as Admin (right-click -> Run as Administrator):
![Screenshot 2024-12-07 141928](https://github.com/user-attachments/assets/b0953a25-caef-4a1f-8dfd-08cf5b8ee1bd)

If there's anything else you need, please let me know.

**Comment by gexgd0419** [comment] 2024-12-07 15:58
The problem is that currently the installer doesn't generate logs, and the installer invokes another process `regsvr32` to perform registration. The error code `0x80020009` is `DISP_E_EXCEPTION`, which is too generic.

The only method I can think of now, is to use tools like [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) to log everything happened during installation, and then check the log to try to get something useful.

You can filter by Process Name, and only include processes named `Installer.exe` and `regsvr32.exe`. Check if there's any operation that failed with result "ACCESS DENIED", which may mean that permission is required for this operation.

Or if you want, you can save the log and send the log file to me via E-mail. Note that Process Monitor logs may include some sensitive information.

**Comment by Darkcyde13** [comment] 2024-12-07 20:55
I was thinking about this, and decided to move the folder to other locations and test.

I first moved it to the root of C: and it works!  So I've tried other locations, ranging from other drives and various directories.  It worked just as it should in every place EXCEPT within the My Documents folder.

For reference, the `E:\Jay's Documents\Games Info\Elite Dangerous\EDDI\NaturalVoiceSAPIAdapter` is within the My Documents folder, I just moved the Windows location from drive C: to be `E:\Jay's Documents`.

Testing further, I put it in this new folder: `E:\This Is A Test\NaturalVoiceSAPIAdapter`, and this works fine as expected.  I then added an apostrophe to the folder name: `E:\This's A Test\NaturalVoiceSAPIAdapter`, because my 'My Documents' folder path has one.  And there it failed!

So, it seems that for whatever reason, it doesn't like the apostrophe in the folder path.  Could this be something to do with how that code has been progammed into the installer?  I know a little about coding, and I know that using quote marks or apostrophe's ( " or ' ) can break code when handling strings if the string also contains one, and that they need to be 'escaped' (usually with a slash / ) so the compiler/interpreter knows how to handle them.

Can you see if you can replicate the error if you use an apostrophe in the folder path, to confirm (or deny) my findings?

**Comment by gexgd0419** [comment] 2024-12-08 12:43
Thanks very much for your investigation!

Yes, it's the apostrophe (single quote) that causes this issue. Because I'm using ATL, and the registry script (which defines the registry keys/values to create during registration) uses single quotes to delimit strings:

```
HKCR
{
	NoRemove CLSID
	{
		ForceRemove {013ab33b-ad1a-401c-8bee-f6e2b046a94e} = s 'TTSEngine class'
		{
			InprocServer32 = s '%MODULEPATH%'
			{
				val ThreadingModel = s 'Both'
			}
			TypeLib = s '{19d3bf0c-aad3-4348-8fc3-bd439f0da852}'
			Version = s '0.1'
		}
	}
}
```

The `%MODULEPATH%` will be replaced by the DLL's path before ATL parses the script and performs registration.

Older versions uses the built-in `%MODULE%` variable, so single quotes are handled correctly by ATL. Newer versions uses a custom variable `%MODULEPATH%`, because when installing the ARM64 version, the path of `Arm64XForwarder.dll` will be used instead. My code fills the DLL path into the variable, but doesn't check for single quotes, so if there's a single quote in the path, script parsing will fail.

A fix for this issue will be in the next release.

**Comment by Darkcyde13** [comment] 2024-12-08 13:07
Thank you for the explanation.  I'm more of an Excel VBA and Cottle (an obscure scripting language) coder.  Both are rather similar in their structure and commands.  I've tried to learn C#, but got bored of the tutorials. 😆 

I'm glad I could help, and also glad that it's not a fault on my PC.  I'd hate to try figuring that out if it had been!

I'll look forward to your new version then, and thank you for making this.  I use it to add more voices to a 3rd party app for the game Elite Dangerous, called EDDI.  It voices custom scripts that trigger from in-game events, and having additional voices adds greatly to the experience, so thank you very much! 😊

**Closed** 2024-12-09 04:56 UTC
